### ISSUE TITLE
No module named requests in QGIS

### ISSUE THREAD

**Issue by MichauSm** [MicheleTobias/LiteratureMapper#3] opened 2015-10-14 07:37 UTC
Your plugin looks like useful, I'm a geobotanist working with literature too. But when trying to install LiteratureMapper in QGIS 2.10.1 Pisa (Linux) I got corrupted plugin message "No module named requests". Install is unsucessfull. Maybe some other modules need to be installed? Regards from Poland, Michal.

**Comment by MicheleTobias** [comment] 2015-10-14 14:56
Thanks, Michal.  This is a duplicate of a ticket/issue that I submitted yesterday.  We're working on it and should have it fixed this week.

**Closed** 2015-10-14 14:56 UTC

**Comment by MicheleTobias** [comment] 2015-10-14 15:10
If you're anxious to give the plugin a try, you can install Requests yourself: http://docs.python-requests.org/en/latest/
